# Cerbos Configuration
server:
  httpListenAddr: ":3593"
  grpcListenAddr: ":3592"
  
  # CORS configuration for browser-based clients
  cors:
    allowedOrigins:
      - http://localhost:3000
      - http://localhost:8080
    allowedHeaders:
      - "*"
    
# Storage configuration
storage:
  driver: "disk"
  disk:
    directory: "/policies"
    watchForChanges: true

# Audit logging
audit:
  enabled: true
  backend: "local"
  local:
    storagePath: "/tmp/cerbos/audit"

# Schema validation
schema:
  enforcement: reject

# Admin API configuration  
admin:
  enabled: true
  
# Telemetry
telemetry:
  disabled: false