global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # API Gateway Metrics
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Entitlement Service Metrics
  - job_name: 'entitlement-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Workflow Service Metrics
  - job_name: 'flowable-core-workflow'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  # OneCMS Service Metrics
  - job_name: 'onecms-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Service Registry (Eureka)
  - job_name: 'service-registry'
    static_configs:
      - targets: ['host.docker.internal:8761']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']