---
apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "1_0"
  resource: "workflow"
  
  rules:
    # Admin users can do everything
    - actions: ['*']
      roles: ['admin', 'system-admin']
      effect: ALLOW

    # EO Head can register and deploy workflows  
    - actions: ['register', 'deploy', 'view']
      roles: ['eo-head']
      effect: ALLOW

    # Investigation Managers can view workflows
    - actions: ['view']
      roles: ['investigation-manager']
      effect: ALLOW
      
    # CSIS Managers can view workflows
    - actions: ['view'] 
      roles: ['csis-manager']
      effect: ALLOW

    # Default deny for all other actions
    - actions: ['*']
      roles: ['*']
      effect: DENY